using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Xml.Linq;

namespace Licorp_CombineCAD.Services
{
    public class SheetSetService
    {
        public bool CreateSheetSet(string dwgPath, List<string> layoutNames, string dstPath)
        {
            if (string.IsNullOrEmpty(dwgPath) || layoutNames == null || layoutNames.Count == 0)
                return false;

            try
            {
                var ns = "urn:schemas-autodesk-com:SheetSet";

                var root = new XElement(XName.Get("SheetSet", ns),
                    new XAttribute("xmlns", ns),
                    new XElement(XName.Get("Name", ns), "Combined Sheets"),
                    new XElement(XName.Get("Description", ns), "Auto-generated by Licorp CombineCAD"),
                    new XElement(XName.Get("SheetSubset", ns),
                        layoutNames.ConvertAll(name =>
                            new XElement(XName.Get("Sheet", ns),
                                new XAttribute("Layout", name),
                                new XAttribute("FilePath", dwgPath)
                            )
                        )
                    )
                );

                var doc = new XDocument(new XDeclaration("1.0", "UTF-8", null), root);
                doc.Save(dstPath);

                Debug.WriteLine($"[SheetSet] Created: {dstPath} with {layoutNames.Count} layouts");
                return true;
            }
            catch (System.Exception ex)
            {
                Debug.WriteLine($"[SheetSet] Error: {ex.Message}");
                return false;
            }
        }
    }
}
